import React from 'react';
import AutoHeightWebView from 'react-native-autoheight-webview';

function Content({content, style}) {
  function htmlTemplate(content) {
    return `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head><body>${content}</body></html>`;
  }
  return (
    <AutoHeightWebView
      style={{...style}}
      customStyle={`html {line-height: 1.4;-webkit-text-size-adjust: 100%;font-size: 15px;}body {margin: 0;padding: 0 25px;color: #666;font-family: Helvetica, sans-serif;}main {display: block;}h1 {font-size: 2em;margin: 0.67em 0;}hr {box-sizing: content-box;height: 0;overflow: visible;}pre {font-family: monospace, monospace;font-size: 1em;}a {background-color: transparent;}abbr[title] {border-bottom: none;text-decoration: underline;text-decoration: underline dotted;}b,strong {font-weight: bolder;color: #444;}code,kbd,samp {font-family: monospace, monospace;font-size: 1em;}small {font-size: 80%;}sub,sup {font-size: 75%;line-height: 0;position: relative;vertical-align: baseline;}sub {bottom: -0.25em;}sup {top: -0.5em;}img {border-style: none;}button,input,optgroup,select,textarea {font-family: inherit;font-size: 100%;line-height: 1.15;margin: 0;}button,input {overflow: visible;}button,select {text-transform: none;}button,[type="button"],[type="reset"],[type="submit"] {-webkit-appearance: button;}button::-moz-focus-inner,[type="button"]::-moz-focus-inner,[type="reset"]::-moz-focus-inner,[type="submit"]::-moz-focus-inner {border-style: none;padding: 0;}button:-moz-focusring,[type="button"]:-moz-focusring,[type="reset"]:-moz-focusring,[type="submit"]:-moz-focusring {outline: 1px dotted ButtonText;}fieldset {padding: 0.35em 0.75em 0.625em;}legend {box-sizing: border-box;color: inherit;display: table;max-width: 100%;padding: 0;white-space: normal;}progress {vertical-align: baseline;}textarea {overflow: auto;}[type="checkbox"],[type="radio"] {box-sizing: border-box;padding: 0;}[type="number"]::-webkit-inner-spin-button,[type="number"]::-webkit-outer-spin-button {height: auto;}[type="search"] {-webkit-appearance: textfield;outline-offset: -2px;}[type="search"]::-webkit-search-decoration {-webkit-appearance: none;}::-webkit-file-upload-button {-webkit-appearance: button;font: inherit;}details {display: block;}summary {display: list-item;}template {display: none;}[hidden] {display: none;}ul,ol{padding-left: 15px;margin: 0;}li{margin-bottom: 5px;}h1,h2,h3,h4,h5,h6{color: #444;}`}
      originWhitelist={['*']}
      source={{
        html: htmlTemplate(
          `<div><strong>TURK Aİ YAPAY ZEKA BİLİŞİM VE YAZILIM SİSTEMLERİ A.Ş.</strong></div><div><br></div><div>Tepe Prime ve Bilkent CyberPark ofislerimizde bizimle birlikte çalışacak takım arkadaşları aramaktayız.&nbsp;</div><div><br></div><div><strong>GENEL ÖZELLİKLER</strong></div><div><br></div><ul><li>Türkiye Cumhuriyeti Vatandaşı olmak.</li><li>Disiplinli, üretken, samimi, genç ve dinamik bir yapıya sahibiz.&nbsp;</li><li>Bize katılarak ülkemizin geleceğine yön vermek isteyen çalışkan, kendi öğrenebilen, öz motivasyonu ve sorumluluk duygusu yüksek, <strong>yoğun tempoda çalışabilen, önceliği iş ve başarmak olan</strong> arkadaşları beklemekteyiz.</li><li>Erkek adaylar için askerlik hizmetini tamamlamış ya da en az 1 yıl tecilli olmak.</li><li>Savunma Sanayi ve Kamu Güvenliği projelerimiz nedeniyle başvurusu olumlu değerlendirilen adaylar işe başladıktan sonra detaylı güvenlik soruşturması yapılacaktır.</li><li>Mesai saatlerimiz hafta içi 08:00-12:00 ve 13:00-18:00 arasındadır.</li><li>Gerektiğinde hafta içi ve/veya hafta sonu mesai yapmaktayız.</li></ul><div><br></div><div><br></div><div><strong>TEKNİK ÖZELLİKLER</strong></div><div><br></div><ul><li>Tercihen Üniversitelerin Bilgisayar Mühendisliği bölümünden mezun olmak.</li><li>Git konusunda tecrübeli olmak.</li><li>Web servisleri hakkında tecrübeli olmak, RESTFUL API ile entegre uygulama geliştirebilmek.</li><li>Kullanıcı deneyimi ve mobil arayüz tasarım desenleri hakkında tecrübeli olmak ve mobil uygulama için tasarım çıkarabilmek.</li><li>Hızlı ve kaliteli uygulama geliştirebilmek.</li><li>Java/<strong>Kotlin</strong>, OOP, Design Patterns konularına hakim olmak.</li><li>Firebase, Gradle konularında tecrübeli olmak.</li><li>Android Jetpack (Navigation Component, Live Data), RxJava2 kullanabilmek.</li><li>Geliştirilmiş birden fazla projesi markette halen yayında olmak.</li><li>En az 3 yıl Android Uygulama geliştirme tecrübesi olmak.</li></ul><div><br></div><div><strong>Başvuruların info@turkai.com adresine CV ile birlikte yapılması gerekmektedir.</strong></div>`,
        ),
      }}
    />
  );
}

export default Content;
